### ISSUE TITLE
Adding Images

### ISSUE THREAD

**Issue by maniacmusic** [TerabyteTiger/gridsome-airtable-starter#1]
First of all thanks for the great template, I tried a lot and this got me the furthest so far; I don't seem to get the images loaded though. 
I'm trying to add an image from headerImage to each event.
Using {{event.headerImage}} returns like this: "https://dl.airtable.com/.attachments/e16f3b7f246a5c06632b4bd33df7f729/4002e884/image.png" } ]
.

I'm not sure what to do next.

**Comment by TerabyteTiger** [comment]
Glad you like it! 😄 

So because Airtable stores images in a field with multiple uploads available, it's being returned as an array of image urls. 

As an example, you can add the following to `~/components/EventCard.vue` anywhere inside the first `div` to see how processing an image would work:
```
      <img :src="event.headerImage[0].url" width="100" height="100" fit="contain"/>
```
