### ISSUE TITLE
Updated the airtable data, and replicated table but not_found

### ISSUE THREAD

**Issue by greddy4** [TerabyteTiger/gridsome-airtable-starter#7]
Hi, 

Thank you for the gridsome starter. I am trying to learn and updated the airtable keys in a .env file. Without the airtable data, it gives an error about airtable API, and as soon as I add the .env file with credentials, it gives an NOT_FOUND error. 

>Gridsome develop
Gridsome v0.6.7

Initializing plugins...
Initialize - 2.23s
Could not find what you are looking for(NOT_FOUND)[Http code 404]

Any help with the error?

**Comment by TerabyteTiger** [comment]
Based on [Airtable's Error Details page](https://airtable.com/appONDPKMbW0PbHNI/api/docs#curl/errors:usererrorcodes) it sounds like your Base ID might be incorrect. 

![404 Error, route or resource is not found. This error is returned when the request hits an undefined route, or if the resource doesn't exist.](https://user-images.githubusercontent.com/16465776/85048964-0eb6e500-b162-11ea-9dd2-bc975c365ffe.png)
 
Can you double check that the value you have for `AIRTABLE_BASE` came from the URL after selecting your base here: https://airtable.com/api.

**Comment by greddy4** [comment]
I tried it both ways. From the API page for the base, there is one value, and from the base page 
With the airtable.com/api page, the base ID chosen gives an error
`Could not find table Events in application applPl2B8QqxhBUX8(NOT_FOUND)[Http code 404]`

**Comment by TerabyteTiger** [comment]
Could you send a screenshot of your Events table?

**Comment by greddy4** [comment]
Hey Tyler, 
I started the process from the start. I realized I had mislabeled the AIRTABLE_BASE name for the previous error.

Steps:
1. Download/Fork repo
2. CD folder
3. Run `yarn`
4. Run `gridsome develop` 
5. Add .env file
6. Run `gridsome develop` 

current error:
` error  in ./src/templates/Event.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "attachments" on type "Event".

GraphQL request:107:5
106 |     notes
107 |     attachments {
    |     ^
108 |       id ` 

Screenshot of the Events table: 
![image](https://user-images.githubusercontent.com/62607582/85553910-b6ca2380-b624-11ea-9541-ddf9717989b7.png)


Thank you for replying. Looking forward to getting this running. A bit more context on the project I am working on, is to create a simple app to reflect the community actions that have come up during the crisis. This trend will continue to grow where local communities organise more initiatives, and we want to create a simple app where they can add the initiatives, and people in the area can find the help they need. https://connactions.netlify.app/

Regards,

**Comment by TerabyteTiger** [comment]
Thanks for bringing this to my attention. 

It looks like there was an update to the Airtable plugin that requires adjustments to `gridsome.config.js`

I'll follow-up when I have a working example again. 

Aside: Your project sounds great! Look forward to seeing what you do with it!

**Comment by TerabyteTiger** [comment]
Pushed changes to get things back up and running. 

I'll update the docs later to be accurate again, but if you start fresh (again - sorry about that) you _should_ be able to get up and running. 

The biggest issue I see short term is that the URL names are no longer very pretty and use the record ID instead of the Event `name` field.

**Comment by TerabyteTiger** [comment]
README.md is now up to date to correspond with the updated plugin format. I still need to fix up the slugs for the template pages, but at least is useable again. 

Let me know if you still have problems after making the changes!
